# Theme
palette = 0=#0e2133
palette = 1=#d96c75
palette = 2=#7aa89f
palette = 3=#d39834
palette = 4=#6a95df
palette = 5=#9a7fd1
palette = 6=#6bb6c9
palette = 7=#c0caf5
palette = 8=#254761
palette = 9=#f08a93
palette = 10=#98cbbf
palette = 11=#f2d28b
palette = 12=#9db9f5
palette = 13=#b59af0
palette = 14=#8bd3e6
palette = 15=#ffffff

background = #0B1C2B
foreground = #c0caf5
selection-background = #264f78
selection-foreground = #c0caf5

# Background
background-opacity = 0.95
background-blur = true

# Cursor
cursor-color = #ffd700
custom-shader = shaders/cursor_sweep.glsl
