[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "cd ~/Downloads"
desc = "Go to Downloads"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "cd ~/Pictures"
desc = "Go to Pictures"

[[mgr.prepend_keymap]]
on = [ "g", "v" ]
run = "cd ~/Videos"
desc = "Go to Videos"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "cd ~/.local/share/Trash/files"
desc = "Go to Trash"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders"

[[mgr.prepend_keymap]]
on = "t"
run = "tab_create --current"
desc = "Create a new tab in CWD"

[[mgr.prepend_keymap]]
on = [ "t", "r" ]
run = "noop"
desc = "Disable rename tab"

[[mgr.prepend_keymap]]
on = "!"
run = "tab_switch 0"
desc = "Switch to first tab"

[[mgr.prepend_keymap]]
on = "@"
run = "tab_switch 1"
desc = "Switch to second tab"

[[mgr.prepend_keymap]]
on = "#"
run = "tab_switch 2"
desc = "Switch to third tab"

[[mgr.prepend_keymap]]
on = "$"
run = "tab_switch 3"
desc = "Switch to fourth tab"

[[mgr.prepend_keymap]]
on = "%"
run = "tab_switch 4"
desc = "Switch to fifth tab"

[[mgr.prepend_keymap]]
on = "^"
run = "tab_switch 5"
desc = "Switch to sixth tab"

[[mgr.prepend_keymap]]
on = "&"
run = "tab_switch 6"
desc = "Switch to seventh tab"

[[mgr.prepend_keymap]]
on = "*"
run = "tab_switch 7"
desc = "Switch to eighth tab"

[[mgr.prepend_keymap]]
on = "("
run = "tab_switch 8"
desc = "Switch to ninth tab"

[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"
